version: "3.9"

services:
  mysqldb:
    container_name: mysql
    image: mysql:5.6
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:+
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: mabroukach/achatproject
    container_name: achatproject
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysqldb